services:
  db:
    image: timescale/timescaledb:latest-pg14
    container_name: coach_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: coach_app
    env_file:
      - .env
    ports:
      - "8000:8000"
    environment:
      PYTHONPATH: /app
      DATABASE_URL: ""
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
    volumes:
      - .:/app
    command: uvicorn app.api.main:app --host 0.0.0.0 --port 8000
    depends_on:
      db:
        condition: service_healthy

  bot:
    build: .
    container_name: coach_bot
    env_file:
      - .env
    environment:
      PYTHONPATH: /app
      DATABASE_URL: ""
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      API_URL: http://app:8000
    volumes:
      - .:/app
    command: python chat_interface/telegram_bot.py
    depends_on:
      db:
        condition: service_healthy
      app:
        condition: service_started
