"""add_workout_system_tables

Revision ID: 47abd7f45b2e
Revises: 9868cc9e85b8
Create Date: 2025-10-19 12:56:08.206197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47abd7f45b2e'
down_revision: Union[str, Sequence[str], None] = '9868cc9e85b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workout_type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('intensity_level', sa.Integer(), nullable=False),
    sa.Column('template_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workout_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('workout_type', sa.String(), nullable=False),
    sa.Column('workout_name', sa.String(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('recovery_score_before', sa.Float(), nullable=True),
    sa.Column('fit_file_path', sa.String(), nullable=True),
    sa.Column('workout_data', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['workout_templates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_profile.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workout_preferences',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('preferred_workout_types', sa.Text(), nullable=True),
    sa.Column('preferred_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('max_intensity_level', sa.Integer(), nullable=True),
    sa.Column('weekly_workout_goal', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_profile.user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workout_preferences')
    op.drop_table('workout_history')
    op.drop_table('workout_templates')
    # ### end Alembic commands ###
