"""add telegram_user_id to oauth_sessions

Revision ID: 9868cc9e85b8
Revises: 12ed48508d39
Create Date: 2025-10-08 14:03:59.224238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9868cc9e85b8'
down_revision: Union[str, Sequence[str], None] = '12ed48508d39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oauth_sessions', sa.Column('telegram_user_id', sa.BigInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('oauth_sessions', 'telegram_user_id')
    # ### end Alembic commands ###
