"""Initial migration

Revision ID: a6c410a1b271
Revises: 
Create Date: 2025-09-30 18:26:20.771556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6c410a1b271'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profile',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('garmin_email', sa.String(), nullable=True),
    sa.Column('garmin_password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('activities_hypertable',
    sa.Column('activity_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('activity_type', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_profile.user_id'], ),
    sa.PrimaryKeyConstraint('activity_id')
    )
    op.create_table('sensor_data',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('heart_rate', sa.Integer(), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('power', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_profile.user_id'], ),
    sa.PrimaryKeyConstraint('timestamp')
    )
    op.create_table('user_summary',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('preferred_activity_type', sa.String(), nullable=True),
    sa.Column('activity_frequency', sa.Float(), nullable=True),
    sa.Column('typical_activity_duration', sa.Float(), nullable=True),
    sa.Column('typical_activity_distance', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_profile.user_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_summary')
    op.drop_table('sensor_data')
    op.drop_table('activities_hypertable')
    op.drop_table('user_profile')
    # ### end Alembic commands ###
