"""add ftp to workout preferences

Revision ID: d5238feded44
Revises: 47abd7f45b2e
Create Date: 2025-10-29 08:22:59.825386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5238feded44'
down_revision: Union[str, Sequence[str], None] = '47abd7f45b2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout_preferences', sa.Column('ftp', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout_preferences', 'ftp')
    # ### end Alembic commands ###
